---
title: "Effect of Drugs in E. coli"
output: html_notebook
---
```{r}
chem_gen_db <- dbConnect(RSQLite::SQLite(), "../chem_gen.db")
Experiments <- data.table(dbReadTable(chem_gen_db, "Experiments"))
Ryan_Strains <- data.table(dbReadTable(chem_gen_db, "Ryan_Strains"))
dbDisconnect(chem_gen_db)

today <- "2022-03-15"

Experiments <- Ryan_Strains[Experiments[Date == today], on = .(Organism)]

for (i in unique(Experiments[!is.na(Species), Induced])) {
  this.plot <- 
    ggplot(
      Experiments[
        Induced == i, 
        .(OD600,
          Chemical = paste(Media, Chemical, Dose)), 
        by = .(Time)],
      aes(x = Time, y = OD600, color = Chemical, fill = Chemical)) +
    ylim(0, max(Experiments$OD600)) +
    geom_smooth(formula = y ~ s(x, bs = "cs"), method = "gam") +
    scale_colour_brewer(palette = "Set1") +
    scale_fill_brewer(palette = "Set1") +
    ggtitle(paste("IPTG", i, "mM", "growth curves on", today))
  
  plot(this.plot)
}
```
```{r}
chem_gen_db <- dbConnect(RSQLite::SQLite(), "../chem_gen.db")
Fitted_Experiments <- data.table(dbReadTable(chem_gen_db, "Fitted_Experiments"))
Ryan_Strains <- data.table(dbReadTable(chem_gen_db, "Ryan_Strains"))
dbDisconnect(chem_gen_db)

today <- "2022-03-15"

Fitted_Experiments <- Ryan_Strains[Fitted_Experiments[Date == today], on = .(Organism)]

for (i in unique(Fitted_Experiments[!is.na(Species), Induced])) {
  this.plot <- 
    ggplot(
      Fitted_Experiments[
        Induced == i, 
        .(OD600_fit,
          Chemical = paste(Media, Chemical, Dose)), 
        by = .(Hour)],
      aes(x = Hour, y = OD600_fit, color = Chemical, fill = Chemical)) +
    ylim(0, max(Experiments$OD600)) +
    geom_smooth(formula = y ~ s(x, bs = "cs"), method = "gam") +
    scale_colour_brewer(palette = "Set1") +
    scale_fill_brewer(palette = "Set1") +
    ggtitle(paste("IPTG", i, "mM", "growth curves on", today))
  
  plot(this.plot)
}
```
